### PR TITLE
add api

### LINKED ISSUE #7: API
Need to add minimal API like `smoothScroll.init(options)` and `smoothScroll.destroy()`

### PR DESCRIPTION
**Pull request by TrySound**
fix #7 #5

### CODE REVIEW

**Comment by gblazex** [comment]
Isn't a simple global variable enough?

e.g.: `window.SmoothScrollOptions = { ... }`

I'd like to keep the library as lean as possible.

**Comment by TrySound** [comment]
@galambalazs Global variables aren't good solution. Especially for the node/browserify.

**Comment by gblazex** [comment]
What do you think about this:

``` javascript
/***********************************************
 * PUBLIC INTERFACE
 ***********************************************/

function SmoothScroll(optionsToSet) {
    for (var key in optionsToSet)
        if (defaultOptions.hasOwnProperty(key)) 
            options[key] = optionsToSet[key];
}
SmoothScroll.destroy = cleanup;

if ('object' == typeof exports)
    module.exports = SmoothScroll;
else
    window.SmoothScroll = SmoothScroll;
```

**Comment by gblazex** [comment]
So you can change the options by

```
SmoothScroll({ stepSize: 20 })
```

And destroy SmoothScroll by:

```
SmoothScroll.destroy()
```

**Comment by TrySound** [comment]
@galambalazs Looks good, but how to change for example `options.keyboardSupport` or `options.fixedBackground`

Also there are two the same lines in code

``` js
var options = defaultOptions;
```

``` js
/***********************************************
 * SETTINGS
 ***********************************************/

var options = defaultOptions;
```

**Comment by gblazex** [comment]
That duplicate line will be removed in the next commit.
To change the options you pass your own options object to SmoothScroll as I showed in the first example. 
This can contain any number of keys which you want to be different from the defaults.

**Comment by gblazex** [comment]
added https://github.com/galambalazs/smoothscroll-for-websites/commit/ad93fb2b4f4d9b60e463e876a3c7bb38ffb17709

**Comment by gblazex** [comment]
thanks @TrySound

**Comment by TrySound** [comment]
@galambalazs I mean, that it will be checked before options will be replaced.

**Comment by gblazex** [comment]
oh for fixedBackground you are right.

But keyboard listener is removed if you call `destroy`

**Comment by TrySound** [comment]
@galambalazs One second, I'll make new pr.

**Pull request closed without merging**
