### PR TITLE
Added Firefox support

### PR DESCRIPTION
**Pull request by mountpoint**

### CODE REVIEW

**Comment by gblazex** [comment]
firefox has smooth scrolling as far as I know

**Comment by mountpoint** [comment]
firefox doesn't have very smooth scrolling, as does your script =)

**Comment by gblazex** [comment]
Yes but I'd rather not mess with native scrolling if it's available and reasonably smooth.
Users of that browser are used to that behavior and it's generally not a good idea to give them different experience on a per site basis.

You can still choose to use your own fork of course, but this shouldn't be pushed out to everyone via the master branch.

**Comment by mountpoint** [comment]
Can we add one option? For example:

`SmoothScroll({
        useFirefoxVerySmoothScroll: true
 });`

`useFirefoxVerySmoothScroll` by default is `false`

If not, I would like use my fork in my projects

**Comment by gblazex** [comment]
That sounds reasonable, I'll consider that option.

**Pull request closed without merging**
