### PR TITLE
Create minified version of Smootscroll

### PR DESCRIPTION
**Pull request by filipemerker**
Original Size:     19.65KB
Compiled Size:  6.48KB
Saved 67.00%
via http://closure-compiler.appspot.com/

### CODE REVIEW

**Comment by TrySound** [comment]
@filipemerker Use build tools

**Comment by filipemerker** [comment]
@TrySound there are a lot of use cases where you simply arn't allowed or have no need to use a build tool. The minified version can be a shortcut for those use cases,

**Comment by TrySound** [comment]
@filipemerker For example?

**Comment by filipemerker** [comment]
You take a project from another developer and you need to just add some parallax feature. The project haven't a build tool nor a build folder structure. You got little time for this. You'll just add the minified lib into some "plugins.js" and create your feature. 
Specially older projects have this need.

**Comment by TrySound** [comment]
10 seconds in any folder

``` js
uglifyjs --compress --mangle input.js
```

**Comment by gblazex** [comment]
As @TrySound said it's quite easy to get a minified version.

The latest stable version (full & minified) can also be downloaded from here:
https://cdnjs.com/libraries/smoothscroll

Or if you are already using cdnjs and don't care about the DNS lookup, you can add it directly via the link.

e.g. for 1.4.0: https://cdnjs.cloudflare.com/ajax/libs/smoothscroll/1.4.0/SmoothScroll.min.js

**Pull request closed without merging**
