### PR TITLE
Update and rename README to README.md

### PR DESCRIPTION
**Pull request by webcaetano**
format REAME to markdown
minor change.

### CODE REVIEW

**Comment by webcaetano** [comment]
@galambalazs

**Comment by gblazex** [comment]
I don't see any reason to use Markdown.
The readme is very simple.

**Comment by gblazex** [comment]
I'll think about putting package managers there.
Currently they are listed on the wiki.

**Comment by webcaetano** [comment]
Hmm it's not just markdown thing.
I added bower install instructions and authors.

I don't mind if you don't want.

**Comment by ghost** [comment]
Markdown is more easy to read.
Bower and npm installation instructions is needed.
Those are just 2 lines.

**Comment by gblazex** [comment]
added the install instructions. Thanks for bringing it up.

I like the current format's simplicity so that stays for now.

Cheers

**Pull request closed without merging**
