### PR TITLE
Use SPDX license format

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by gblazex** [comment]
I use a custom LICENSE file because there is one additional paragraph to MIT. Namely:

> The only restriction is to not publish any extension for browsers or 
> native application without getting a written permission first. Otherwise:
> [MIT]

**Comment by graingert** [comment]
This should be `SEE LICENSE IN < filename>`

**Comment by graingert** [comment]
You're also not allowed to modify the MIT licence and title it with "MIT
licence". You should call it "The Smoothscroll Licence" or something.

**Comment by gblazex** [comment]
fixed the format, thanks for the suggestion: https://github.com/galambalazs/smoothscroll-for-websites/commit/a8c02c29264c87dd55515fd9ea6c468c1598fcf9

I think the license is pretty straightforward. For purposes of a native application or browser extension you need a written permission. For using it on your websites (free or commercial ones) it is available as an MIT style license (you can copy, modify, merge, distribute it freely).

**Comment by graingert** [comment]
Looks like you can use the code under the MIT licence then sublicense it under anything else excluding the requirement to not use it in an extension

**Pull request closed without merging**
