### PR TITLE
Improved api

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
All addEvent should be in exports, all removeEvent in cleanup. And now we can on and off smoothscroll.

**Comment by TrySound** [comment]
And new exports calling will destroy firstly and then init again with new options.

**Comment by gblazex** [comment]
Your problem was that some parts of init ran even when you called `destroy`.

That can be solved with 1 change: https://github.com/galambalazs/smoothscroll-for-websites/commit/6f669c639e35a0e9c87e89b7017a99db19a85862

So now SmoothScroll runs by default.
If you want to opt out (e.g. not use it on a certain page) you just call `SmoothScroll.destroy()` (as early as possible)

In what situation would you want to turn it on/off dynamically?

**Comment by TrySound** [comment]
@galambalazs It's just a good architecture for any library. It shouldn't do anything without calling. Everything should be controllable.

**Comment by gblazex** [comment]
I think you show intent by including the library. That should work for 99% of the cases.
If you want to disable on certain pages you got `destroy` now, which covers the remaining 1%.

This is not a utility library, it just patches a behavior already present in other browsers (enabled by default, e.g. Firefox & IE + mobile browsers, etc.)

**Comment by TrySound** [comment]
@galambalazs One more case. I want to have smooth scroll without keyboardsupport. Or why this option if I can't change this?

**Comment by TrySound** [comment]
Even polyfill should have a good API.

**Comment by gblazex** [comment]
I think being ON by default _is_ the good API.

Again, do browsers give you an API to disable smooth scrolling dynamically by JS? No.
It's ON by default for a good reason. This library patches Chrome to do the same behavior.

Opting out is mostly for when you run into compatibility issues (because a JS module cannot be 100% like a native solution).

```
SmoothScroll({ keyboardSupport: false })
```

will give you SS without the keyboard module.

**Comment by TrySound** [comment]
@galambalazs Nope, it won't

**Comment by gblazex** [comment]
Just a sidenote: ON by default also comes from being a Chrome extension.

It's because being disabled on certain sites is done by asking for the user settings. This takes some time.
We don't want to have jerky scrolling until the settings arrive.

So we cover 99% of the cases by having it ON by default (that's why you installed the extension, or included the library) and leave the 1% case of being disabled as something you do by removing the eager initialization's clues.

**Comment by gblazex** [comment]
I think it does, given you called this: 

```
SmoothScroll({ keyboardSupport: false })
```

..._before_ init runs.

Again it's not turning it on/off dynamically. It's about having your custom options ready before init.

```
<script src="SmoothScroll.js"></script>
<script>SmoothScroll({ keyboardSupport: false })</script>
```

**Comment by TrySound** [comment]
Looks weird and too difficult. And this is not chrome extension. What if I want to disable keyboard after everything loaded? Maybe I load modules dinamically with ajax.

**Comment by TrySound** [comment]
And how I can to call SmoothScroll before it defined? It won't work.

**Comment by gblazex** [comment]
That's why I think this would be a sync version:

```
<script src="SmoothScroll.js"></script>
<script>SmoothScroll({ keyboardSupport: false })</script>
```

This could be the async version

```
<script>SmoothScrollOptions = { keyboardSupport: false }</script>
<script async src="SmoothScroll.js"></script>
```

Like Google Analytics does. You have a global variable which you fill up. When the script is loaded (anytime, via script tag or a loader lib, etc.) it checks for the existence of the global var. This is a justified use case.

**Comment by TrySound** [comment]
Okay, what if I load it with bower and use main-bower-files to concatenate everything. User code will be after in any cases, cause changing build to make one lib works is stupid action.

**Comment by gblazex** [comment]
I'm not sure I understand.

If user code runs _before_ library option 2 should work.
If user code runs _after_ library option 1 should work.

Am I missing something?

**Comment by TrySound** [comment]
And I do not want to use async, I want to load it with ajax and call my code on end. In this case init method will not be called never.

**Comment by gblazex** [comment]
You don't have to use `<script async>` :)

That's just a demonstration of the case where user code runs _before_ the library is loaded. You can load it with ajax, it's the same thing.

```
window.SmoothScrollOptions = { keyboardSupport: false }
loadLibrary('SmoothScroll.js') // async loading
```

**Comment by TrySound** [comment]
@galambalazs The node way (also browserify) is not to use global variables. Everything happens inside the modules. And defining variable before library loaded is uncomfortable. Much better just pass an object to method and that's all.

**Comment by gblazex** [comment]
google analytics async 1

``` html
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXXX-Y', 'auto');
ga('send', 'pageview');
</script>
```

google analytics async 2

``` html
<script async src='//www.google-analytics.com/analytics.js'></script>
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-XXXX-Y', 'auto');
ga('send', 'pageview');
</script>
```

Note the use of global variables. This is a proven technique to provide data/options even actions to scripts not yet loaded.

**Comment by gblazex** [comment]
I believe all cases are covered now. 

https://github.com/galambalazs/smoothscroll-for-websites/wiki
https://github.com/galambalazs/smoothscroll-for-websites/commit/3044a9fc28a25c61b72f4fdd4ada51d149a820da

Thanks for all the help.

If you have a specific use-case that you cannot achieve with the current setup let me know.

**Pull request closed without merging**
