### PR TITLE
Added support for require.js

### PR DESCRIPTION
**Pull request by AlexXsWx**

### CODE REVIEW

**Comment by TrySound** [comment]
@AlexXsWx You forgot else statement.

**Comment by AlexXsWx** [comment]
Unfortunately I am not familiar with dependency management systems at all, and don't know if approaches with 'define.amd' and 'module.export' can coexist or not, therefore I did not add the else statement.

**Comment by TrySound** [comment]
@AlexXsWx 

``` js
if ('object' == typeof exports)
    module.exports = SmoothScroll;
else
if(typeof define === "function" && define.amd)
    define(function() {
        return SmoothScroll;
    });
else
    window.SmoothScroll = SmoothScroll;
```

**Comment by AlexXsWx** [comment]
Thanks. Although, if I get it right, it will break projects that are using requirejs (and so having `define.amd`) and somehow worked around the import via `window.SmoothScroll`. But that should be good point to fix the workaround.

**Comment by TrySound** [comment]
@AlexXsWx Also do you know how to squash commits?

**Comment by AlexXsWx** [comment]
Updated; thanks.

**Comment by gblazex** [comment]
looks good

If you can put the AMD check first and put `else if` words on the same line I can merge this.

> ...some build tools that expose an _exports_ object, which might cause things to break if the CommonJS check happens before the AMD check

http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/

**Comment by AlexXsWx** [comment]
Fixed; thanks for the link

**Pull request merged**
